Feature/version history
topi314/gobin pull request #8
Opened 2023-02-13 04:03 UTC by day-mon

2023-02-14 17:54 UTC, Sanduhr32 reviewed
funny

2023-02-14 17:54 UTC, Sanduhr32 commented on assets/script.js
>  })
extract the string and call doKeyboardAction() once

2023-02-15 10:20 UTC, TopiSenpai requested changes

2023-02-15 10:20 UTC, TopiSenpai commented on routes.go
> +	r.Get("/document/{documentID}/versions", s.DocumentVersions)
should be `/documents/{documentID}/versions`

2023-02-15 10:20 UTC, TopiSenpai commented on routes.go
> +func (s *Server) DeleteDocumentByVersion(w http.ResponseWriter, r *http.Request) {
should be `DeleteDocumentVersion`

2023-02-15 10:20 UTC, TopiSenpai commented on routes.go
> +func sanitizeDocumentWithVersion(r *http.Request, s *Server, w http.ResponseWriter) (string, int64) {
should be `parseDocumentVersion`

2023-02-15 10:20 UTC, TopiSenpai commented on database.go
> +	// TODO:this should do an insert with a new version now
this to do is done

2023-02-15 10:20 UTC, TopiSenpai commented on database.go
> +	res, err := d.ExecContext(ctx, "DELETE FROM documents WHERE version = $1 AND id = $2", version, documentID)
should be `DeleteDocumentByVersion(ctx context.Context, documentID string, version int64)`

2023-02-15 10:20 UTC, TopiSenpai commented on database.go
> +func (d *Database) GetDocumentByVersion(ctx context.Context, id string, version int64) (Document, error) {
should be `GetDocumentByVersion(ctx context.Context, documentID string, version int64)`

2023-02-15 10:20 UTC, TopiSenpai commented on database.go
> +func (d *Database) GetDocumentVersions(ctx context.Context, id string, withContent bool) ([]Document, error) {
should be `GetDocumentVersions(ctx context.Context, documentID string, withContent bool)`

2023-03-03 14:24 UTC, TopiSenpai approved these changes

2023-03-03 19:02 UTC, merged